=== JoeAlisson/L2J/Datapack/data/stats/item.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://la2j.org"
           xmlns="http://la2j.org"
           elementFormDefault="qualified">

    <xs:include schemaLocation="stat.xsd"/>

    <xs:element name="itemList">
        <xs:complexType>
            <xs:choice>
                <xs:element name="item" type="xmlTypeItemStat" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
        </xs:complexType>

    </xs:element>

    <xs:complexType name="xmlTypeItemStat">
        <xs:sequence>
            <xs:element name="stat" type="xmlTypeStat" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:int" use="required"/>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

</xs:schema>

=== JoeAlisson/L2J/Datapack/data/stats/weapon/3900-3999.xml
<?xml version='1.0' encoding='utf-8'?>
<itemList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://la2j.org"
          xsi:schemaLocation="http://la2j.org ../item.xsd">
    <item id='3902' name="ghost_canine">

        <stat function='add' value='11' order='16' name='PHYSIC_ATTACK'/>
        <stat function='add' value='10' order='16' name='MAGIC_ATTACK'/>
        <stat function='add' value='80' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='304' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
    <item id='3903' name="mithril_canine">

        <stat function='add' value='16' order='16' name='PHYSIC_ATTACK'/>
        <stat function='add' value='14' order='16' name='MAGIC_ATTACK'/>
        <stat function='add' value='80' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='304' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
    <item id='3904' name="sylvan_canine">

        <stat function='add' value='23' order='16' name='PHYSIC_ATTACK'/>
        <stat function='add' value='18' order='16' name='MAGIC_ATTACK'/>
        <stat function='add' value='80' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='304' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
    <item id='3905' name="orikarukon_canine">

        <stat function='add' value='31' order='16' name='PHYSIC_ATTACK'/>
        <stat function='add' value='24' order='16' name='MAGIC_ATTACK'/>
        <stat function='add' value='80' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='304' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
    <item id='3906' name="fang_of_saltydog">

        <stat function='add' value='40' order='16' name='PHYSIC_ATTACK'/>
        <stat function='add' value='30' order='16' name='MAGIC_ATTACK'/>
        <stat function='add' value='80' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='304' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
    <item id='3907' name="fang_of_cerberus">

        <stat function='add' value='49' order='16' name='PHYSIC_ATTACK'/>
        <stat function='add' value='36' order='16' name='MAGIC_ATTACK'/>
        <stat function='add' value='80' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='304' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
    <item id='3908' name="fang_of_coyote">

        <stat function='add' value='58' order='16' name='PHYSIC_ATTACK'/>
        <stat function='add' value='42' order='16' name='MAGIC_ATTACK'/>
        <stat function='add' value='80' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='304' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
    <item id='3909' name="crystalized_ice_canine">

        <stat function='add' value='69' order='16' name='PHYSIC_ATTACK'/>
        <stat function='add' value='50' order='16' name='MAGIC_ATTACK'/>
        <stat function='add' value='80' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='304' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
    <item id='3910' name="fang_of_the_blue_wolf">

        <stat function='add' value='80' order='16' name='PHYSIC_ATTACK'/>
        <stat function='add' value='58' order='16' name='MAGIC_ATTACK'/>
        <stat function='add' value='80' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='304' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
    <item id='3911' name="fang_of_fenril">

        <stat function='add' value='93' order='16' name='PHYSIC_ATTACK'/>
        <stat function='add' value='66' order='16' name='MAGIC_ATTACK'/>
        <stat function='add' value='80' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='304' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
    <item id='3919' name="serpent_fang">

        <stat function='add' value='8' order='16' name='PHYSIC_ATTACK'/>
        <stat function='add' value='7' order='16' name='MAGIC_ATTACK'/>
        <stat function='add' value='80' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='304' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
    <item id='3920' name="viperbite">

        <stat function='add' value='9' order='16' name='PHYSIC_ATTACK'/>
        <stat function='add' value='10' order='16' name='MAGIC_ATTACK'/>
        <stat function='add' value='80' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='304' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
    <item id='3921' name="shadow_fang">

        <stat function='add' value='10' order='16' name='PHYSIC_ATTACK'/>
        <stat function='add' value='11' order='16' name='MAGIC_ATTACK'/>
        <stat function='add' value='80' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='304' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
    <item id='3922' name="alya_fang">

        <stat function='add' value='12' order='16' name='PHYSIC_ATTACK'/>
        <stat function='add' value='13' order='16' name='MAGIC_ATTACK'/>
        <stat function='add' value='80' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='304' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
    <item id='3923' name="torturer">

        <stat function='add' value='13' order='16' name='PHYSIC_ATTACK'/>
        <stat function='add' value='16' order='16' name='MAGIC_ATTACK'/>
        <stat function='add' value='80' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='304' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
    <item id='3924' name="unuk_alhay_fang">

        <stat function='add' value='15' order='16' name='PHYSIC_ATTACK'/>
        <stat function='add' value='18' order='16' name='MAGIC_ATTACK'/>
        <stat function='add' value='80' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='304' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
    <item id='3925' name="antiplague">

        <stat function='add' value='17' order='16' name='PHYSIC_ATTACK'/>
        <stat function='add' value='21' order='16' name='MAGIC_ATTACK'/>
        <stat function='add' value='80' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='304' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
    <item id='3937' name="giant_bar">

        <stat function='add' value='50' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='26' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='8' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='66' order='8' name='PHYSIC_ATTACK_RANGE'/>
        <stat function='add' value='-3' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='3938' name="giant_rod">

        <stat function='add' value='50' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='26' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='8' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='66' order='8' name='PHYSIC_ATTACK_RANGE'/>
        <stat function='add' value='-3' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='3939' name="ladys_fan">

        <stat function='add' value='50' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='26' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='8' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='66' order='8' name='PHYSIC_ATTACK_RANGE'/>
        <stat function='add' value='-3' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
</itemList>

=== JoeAlisson/L2J/Datapack/data/stats/weapon/1100-1199.xml
<?xml version='1.0' encoding='utf-8'?>
<itemList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"           xmlns="http://la2j.org" xsi:schemaLocation="http://la2j.org ../item.xsd">
<item id='1142' name="rusted_bronze_sword">

    <stat function='add' value='18' order='8' name='PHYSIC_ATTACK'/>
    <stat function='add' value='21' order='8' name='MAGIC_ATTACK'/>
    <stat function='add' value='8' order='8' name='CRITICAL_RATE'/>
    <stat function='add' value='0' order='16' name='ACCURACY'/>
    <stat function='add' value='379' order='8' name='PHYSIC_ATTACK_SPEED'/>
    <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
    <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

</item>
<item id='1181' name="netis_bow">

    <stat function='add' value='45' order='8' name='PHYSIC_ATTACK'/>
    <stat function='add' value='16' order='8' name='MAGIC_ATTACK'/>
    <stat function='add' value='12' order='8' name='CRITICAL_RATE'/>
    <stat function='add' value='-3' order='16' name='ACCURACY'/>
    <stat function='add' value='293' order='8' name='PHYSIC_ATTACK_SPEED'/>
    <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
    <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

</item>
<item id='1182' name="netis_dagger">

    <stat function='add' value='19' order='8' name='PHYSIC_ATTACK'/>
    <stat function='add' value='16' order='8' name='MAGIC_ATTACK'/>
    <stat function='add' value='12' order='8' name='CRITICAL_RATE'/>
    <stat function='add' value='-3' order='16' name='ACCURACY'/>
    <stat function='add' value='433' order='8' name='PHYSIC_ATTACK_SPEED'/>
    <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
    <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

</item>
</itemList>

=== JoeAlisson/L2J/Datapack/data/stats/armor/1500-1599.xml
<?xml version='1.0' encoding='utf-8'?>

<itemList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://la2j.org" xsi:schemaLocation="http://la2j.org ../item.xsd">

    <item id='1506' name="Necklace of Courage">
        <stat function='add' order='16' name='MAGIC_DEFENCE' value='15'/>
    </item>
    <item id='1507' name="Necklace of Valor">
        <stat function='add' order='16' name='MAGIC_DEFENCE' value='21'/>
    </item>
    <item id='1508' name="Ring of Raccoon">
        <stat function='add' order='16' name='MAGIC_DEFENCE' value='11'/>
    </item>
    <item id='1509' name="Ring of Firefly">
        <stat function='add' order='16' name='MAGIC_DEFENCE' value='11'/>
    </item>
</itemList>

=== JoeAlisson/L2J/Datapack/data/stats/weapon/7900-7999.xml
<?xml version='1.0' encoding='utf-8'?>
<itemList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"           xmlns="http://la2j.org" xsi:schemaLocation="http://la2j.org ../item.xsd">
<item id='7900' name="ice_storm_hammer">

    <stat function='add' value='213' order='8' name='PHYSIC_ATTACK'/>
    <stat function='add' value='91' order='8' name='MAGIC_ATTACK'/>
    <stat function='add' value='4' order='8' name='CRITICAL_RATE'/>
    <stat function='add' value='4' order='16' name='ACCURACY'/>
    <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>
    <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
    <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

</item>
<item id='7901' name="star_buster">

    <stat function='add' value='236' order='8' name='PHYSIC_ATTACK'/>
    <stat function='add' value='99' order='8' name='MAGIC_ATTACK'/>
    <stat function='add' value='4' order='8' name='CRITICAL_RATE'/>
    <stat function='add' value='4' order='16' name='ACCURACY'/>
    <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>
    <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
    <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

</item>
<item id='7902' name="doom_crusher">

    <stat function='add' value='282' order='8' name='PHYSIC_ATTACK'/>
    <stat function='add' value='114' order='8' name='MAGIC_ATTACK'/>
    <stat function='add' value='4' order='8' name='CRITICAL_RATE'/>
    <stat function='add' value='4' order='16' name='ACCURACY'/>
    <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>
    <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
    <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

</item>
<item id='7903' name="(monster_only)frintessa_follower_calibur">

    <stat function='add' value='78' order='8' name='PHYSIC_ATTACK'/>
    <stat function='add' value='39' order='8' name='MAGIC_ATTACK'/>
    <stat function='add' value='8' order='8' name='CRITICAL_RATE'/>
    <stat function='add' value='0' order='16' name='ACCURACY'/>
    <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>

</item>
</itemList>

=== JoeAlisson/L2J/Datapack/data/stats/weapon/7500-7599.xml
<?xml version='1.0' encoding='utf-8'?>
<itemList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://la2j.org"
          xsi:schemaLocation="http://la2j.org ../item.xsd">
    <item id='7560' name="monster_only_(fishing_rod)">

        <stat function='add' value='1' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='1' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='0' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='-3' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='7575' name="draconic_bow">

        <stat function='add' value='581' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='132' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='12' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='-3' order='16' name='ACCURACY'/>
        <stat function='add' value='293' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='7576' name="draconic_bow_cheap_shot">

        <stat function='add' value='581' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='132' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='12' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='-3' order='16' name='ACCURACY'/>
        <stat function='add' value='293' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>
        <!-- SA: Cheap Shot -->
        <stat function='set' value='1' order='8' name='MP_CONSUME'>
            <conditions>
                <and>
                    <game kind="skill" value="false"/>
                    <game kind="chance" value="26"/>
                </and>
            </conditions>
        </stat>
        <!-- Enhances damage to target during PvP -->
        <stat function='mul' value='1.05' order='48' name='PVP_PHYSIC_DAMAGE'/>
        <stat function='mul' value='1.05' order='48' name='PVP_MAGIC_DAMAGE'/>

    </item>
    <item id='7577' name="draconic_bow_focus">

        <stat function='add' value='581' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='132' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='12' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='-3' order='16' name='ACCURACY'/>
        <stat function='add' value='293' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>
        <!-- SA: Focus -->
        <stat function='add' value='88' order='64' name='CRITICAL_RATE'/>
        <!-- Enhances damage to target during PvP -->
        <stat function='mul' value='1.05' order='48' name='PVP_PHYSIC_DAMAGE'/>
        <stat function='mul' value='1.05' order='48' name='PVP_MAGIC_DAMAGE'/>

    </item>
    <item id='7578' name="draconic_bow_critical_slow">

        <stat function='add' value='581' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='132' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='12' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='-3' order='16' name='ACCURACY'/>
        <stat function='add' value='293' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>
        <!-- Enhances damage to target during PvP -->
        <stat function='mul' value='1.05' order='48' name='PVP_PHYSIC_DAMAGE'/>
        <stat function='mul' value='1.05' order='48' name='PVP_MAGIC_DAMAGE'/>
        <!-- SA: Critical Slow -->
        <skill triggerType='onCrit' id='3594' chance='7'/>

    </item>
</itemList>

=== JoeAlisson/L2J/Datapack/data/stats/armor/8900-8999.xml
<?xml version='1.0' encoding='utf-8'?>
<itemList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://la2j.org" xsi:schemaLocation="http://la2j.org ../item.xsd">

    <item id='8910' name="Black Feather Mask - For Event">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='8911' name="Black Half-Mask - For Event">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='8912' name="Single Stem Flower">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='8913' name="Butterfly Hairpin">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='8914' name="Luxurious Gold Circlet">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='8915' name="Luxurious Silver Circlet">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='8916' name="Eye Patch">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='8917' name="Goddess Circlet">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='8918' name="Leather Cap">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='8919' name="Commodore\'s Hat - Event Use">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='8920' name="Angel Halo">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='8921' name="Demon Circlet">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='8922' name="Pirate Hat">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='8923' name="Scar">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='8936' name="Santa\'s Antlers">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='8947' name="L2 Day: Rabbit Ears">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='8948' name="L2 Day: Little Angel Wings">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='8949' name="L2 Day: Fairy Antennae">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='8950' name="L2 Day: Feathered Hat">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='8951' name="L2 Day: Artisan\'s Goggles">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
</itemList>

=== JoeAlisson/L2J/Datapack/data/stats/weapon/5700-5799.xml
<?xml version='1.0' encoding='utf-8'?>
<itemList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://la2j.org"
          xsi:schemaLocation="http://la2j.org ../item.xsd">
    <item id='5704' name="keshanberk*keshanberk">

        <stat function='add' value='259' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='107' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='8' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='0' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='mul' value='1.08' order='48' name='PHYSIC_ATTACK_SPEED'>
            <conditions>
                <using kind='slotitem' item='5704' slot='14' enchantment='4'/>
            </conditions>
        </stat>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='5705' name="keshanberk*damascus">

        <stat function='add' value='275' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='112' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='8' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='0' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='mul' value='1.25' order='48' name='MAX_HP'>
            <conditions>
                <using kind='slotitem' item='5705' slot='14' enchantment='4'/>
            </conditions>
        </stat>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>
        <!-- Enhances damage to target during PvP -->
        <stat function='mul' value='1.05' order='48' name='PVP_PHYSIC_DAMAGE'/>
        <stat function='mul' value='1.05' order='48' name='PVP_MAGIC_DAMAGE'/>

    </item>
    <item id='5706' name="damascus*damascus">

        <stat function='add' value='282' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='114' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='8' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='add' value='6' order='16' name='ACCURACY'>
            <conditions>
                <using kind='slotitem' item='5706' slot='14' enchantment='4'/>
            </conditions>
        </stat>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>
        <!-- Enhances damage to target during PvP -->
        <stat function='mul' value='1.05' order='48' name='PVP_PHYSIC_DAMAGE'/>
        <stat function='mul' value='1.05' order='48' name='PVP_MAGIC_DAMAGE'/>

    </item>
    <item id='5791' name="tomb_guard_a">

        <stat function='add' value='78' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='39' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='8' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='0' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='5792' name="tomb_guard_b">

        <stat function='add' value='78' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='39' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='8' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='0' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='5793' name="tomb_savant_a">

        <stat function='add' value='156' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='83' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='8' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='0' order='16' name='ACCURACY'/>
        <stat function='add' value='379' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='5794' name="tomb_savant_b">

        <stat function='add' value='156' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='83' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='8' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='0' order='16' name='ACCURACY'/>
        <stat function='add' value='379' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='5795' name="tomb_guard_a">

        <stat function='add' value='78' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='39' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='8' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='0' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='5796' name="tomb_guard_b">

        <stat function='add' value='78' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='39' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='8' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='0' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='5797' name="tomb_savant_a">

        <stat function='add' value='156' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='83' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='8' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='0' order='16' name='ACCURACY'/>
        <stat function='add' value='379' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='5798' name="tomb_savant_b">

        <stat function='add' value='156' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='83' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='8' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='0' order='16' name='ACCURACY'/>
        <stat function='add' value='379' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='5799' name="nephilim_lord">

        <stat function='sub' value='8' order='16' name='EVASION_RATE'/>
        <stat function='add' value='142' order='8' name='SHIELD_DEFENCE'/>
        <stat function='add' value='20' order='8' name='SHIELD_RATE'/>
        <stat function='enchant' value='0' order='12' name='SHIELD_DEFENCE'/>

    </item>
</itemList>
