=== JoeAlisson/L2J/Datapack/data/stats/item.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://la2j.org"
           xmlns="http://la2j.org"
           elementFormDefault="qualified">

    <xs:include schemaLocation="stat.xsd"/>

    <xs:element name="itemList">
        <xs:complexType>
            <xs:choice>
                <xs:element name="item" type="xmlTypeItemStat" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
        </xs:complexType>

    </xs:element>

    <xs:complexType name="xmlTypeItemStat">
        <xs:sequence>
            <xs:element name="stat" type="xmlTypeStat" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:int" use="required"/>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

</xs:schema>

=== JoeAlisson/L2J/Datapack/data/stats/weapon/4900-4999.xml
<?xml version='1.0' encoding='utf-8'?>
<itemList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://la2j.org"
          xsi:schemaLocation="http://la2j.org ../item.xsd">
    <item id='4900' name="staff_of_evil_spirit_magic_focus">

        <stat function='add' value='189' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='132' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='4' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='4' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>
        <!-- Magic Focus -->
        <skill triggerType="onCast" id='1077' level='3' chance='20'/>

    </item>
    <item id='4901' name="staff_of_evil_spirit_bodily_blessing">

        <stat function='add' value='189' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='132' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='4' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='4' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>
        <!-- Bodily Blessing -->
        <skill triggerType='onCast' id='1045' level='5' chance='20'/>

    </item>
    <item id='4902' name="staff_of_evil_spirit_magic_poison">

        <stat function='add' value='189' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='132' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='4' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='4' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='4903' name="dasparions_staff">

        <stat function='add' value='207' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='143' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='4' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='4' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>
        <stat function='mul' value='1.25' order='48' name='MAX_HP'/>

    </item>
    <item id='4904' name="dasparions_staff">

        <stat function='add' value='207' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='143' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='4' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='4' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='4905' name="dasparions_staff">

        <stat function='add' value='207' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='143' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='4' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='4' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
</itemList>

=== JoeAlisson/L2J/Datapack/data/stats/armor/9100-9199.xml
<?xml version='1.0' encoding='utf-8'?>

<itemList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://la2j.org" xsi:schemaLocation="http://la2j.org ../item.xsd">

    <item id='9100' name="Shadow Item: Magestic Boots">

        <stat function='add' value='49' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='9101' name="Shadow Item: Magestic Robe">

        <stat function='add' value='147' order='16' name='PHYSIC_DEFENCE'/>
        <stat function='add' value='718' order='96' name='MAX_MP'/>

    </item>
    <item id='9102' name="Shadow Item: Magestic Gauntlet">

        <stat function='add' value='49' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='9103' name="Shadow Item: Magestic Boots">

        <stat function='add' value='49' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='9128' name="Shadow Item: Mithril Gauntlet">

        <stat function='add' value='36' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='9138' name="Santa\'s Hat">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='9145' name="Little Angel Wings - For Event">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='9158' name="Gold Circlet - For Event">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='9159' name="Silver Circlet - For Event">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='9160' name="Medievalue Leather Cap - For Event">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='9177' name="Teddy Bear Hat - Blessed Scroll of Resurrection">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='9178' name="Piggy Hat - Blessed Scroll of Resurrection">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='9179' name="Jester Hat - Blessed Scroll of Resurrection">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='9180' name="Wizard\'s Hat - Blessed Scroll of Resurrection">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='9181' name="Dapper Cap - Blessed Scroll of Resurrection">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='9182' name="Romantic Chapeau - Blessed Scroll of Resurrection">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='9183' name="Iron Circlet - Blessed Scroll of Resurrection">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='9184' name="Teddy Bear Hat - Blessed Scroll of Escape">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='9185' name="Piggy Hat - Blessed Scroll of Escape">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='9186' name="Jester Hat - Blessed Scroll of Escape">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='9187' name="Wizard\'s Hat - Blessed Scroll of Escape">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='9188' name="Dapper Cap - Blessed Scroll of Escape">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='9189' name="Romantic Chapeau - Blessed Scroll of Escape">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='9190' name="Iron Circlet - Blessed Scroll of Escape">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='9191' name="Teddy Bear Hat - Big Head">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='9192' name="Piggy Hat - Big Head">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='9193' name="Jester Hat - Big Head">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='9194' name="Wizard\'s Hat - Big Head">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='9195' name="Dapper Hat - Big Head">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='9196' name="Romantic Chapeau - Big Head">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='9197' name="Iron Circlet - Big Head">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='9198' name="Teddy Bear Hat - Firework">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='9199' name="Piggy Hat - Firework">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
</itemList>

=== JoeAlisson/L2J/Datapack/data/stats/armor/3900-3999.xml
<?xml version='1.0' encoding='utf-8'?>
<itemList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://la2j.org" xsi:schemaLocation="http://la2j.org ../item.xsd">

    <item id='3900' name="Wolf's Luxury Plate">

        <stat function='add' order='16' name='PHYSIC_DEFENCE' value='43'/>
        <stat function='add' order='16' name='MAGIC_DEFENCE' value='38'/>

    </item>
    <item id='3901' name="Wolf's Mithril Armor">

        <stat function='add' order='16' name='PHYSIC_DEFENCE' value='47'/>
        <stat function='add' order='16' name='MAGIC_DEFENCE' value='41'/>

    </item>
    <item id='3912' name="Hatchling's Soft Leather">

        <stat function='add' order='16' name='PHYSIC_DEFENCE' value='26'/>
        <stat function='add' order='16' name='MAGIC_DEFENCE' value='26'/>

    </item>
    <item id='3913' name="Hatchling's Scale Mail">

        <stat function='add' order='16' name='PHYSIC_DEFENCE' value='29'/>
        <stat function='add' order='16' name='MAGIC_DEFENCE' value='29'/>

    </item>
    <item id='3914' name="Hatchling's Brigandine">

        <stat function='add' order='16' name='PHYSIC_DEFENCE' value='31'/>
        <stat function='add' order='16' name='MAGIC_DEFENCE' value='31'/>

    </item>
    <item id='3915' name="Hatchling's Bronze Coat">

        <stat function='add' order='16' name='PHYSIC_DEFENCE' value='33'/>
        <stat function='add' order='16' name='MAGIC_DEFENCE' value='33'/>

    </item>
    <item id='3916' name="Hatchling's Steel Coat">

        <stat function='add' order='16' name='PHYSIC_DEFENCE' value='36'/>
        <stat function='add' order='16' name='MAGIC_DEFENCE' value='36'/>

    </item>
    <item id='3917' name="Hatchling's Shadowplate">

        <stat function='add' order='16' name='PHYSIC_DEFENCE' value='38'/>
        <stat function='add' order='16' name='MAGIC_DEFENCE' value='38'/>

    </item>
    <item id='3918' name="Hatchling's Mithril Coat">

        <stat function='add' order='16' name='PHYSIC_DEFENCE' value='41'/>
        <stat function='add' order='16' name='MAGIC_DEFENCE' value='41'/>

    </item>
</itemList>

=== JoeAlisson/L2J/Datapack/data/stats/armor/6800-6899.xml
<?xml version='1.0' encoding='utf-8'?>

<itemList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://la2j.org" xsi:schemaLocation="http://la2j.org ../item.xsd">

    <item id='6834' name="Circlet of Innadrill">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='6835' name="Circlet of Dion">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='6836' name="Circlet of Goddard">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='6837' name="Circlet of Oren">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='6838' name="Circlet of Gludio">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='6839' name="Circlet of Giran">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='6840' name="Circlet of Aden">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='6841' name="Crown of Lord">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='6842' name="Wings of Destiny Circlet">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='6843' name="Cat Ear">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='6844' name="Lady's Hair Pin">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='6845' name="Pirate's Eye Patch">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='6846' name="Monocle">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
</itemList>

=== JoeAlisson/L2J/Datapack/data/stats/weapon/5100-5199.xml
<?xml version='1.0' encoding='utf-8'?>
<itemList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://la2j.org"
          xsi:schemaLocation="http://la2j.org ../item.xsd">
    <item id='5127' name="dailaon_knife">

        <stat function='add' value='5' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='5' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='12' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='-3' order='16' name='ACCURACY'/>
        <stat function='add' value='433' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='5128' name="crokian_blade">

        <stat function='add' value='5' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='5' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='12' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='-3' order='16' name='ACCURACY'/>
        <stat function='add' value='433' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='5129' name="doll_knife">

        <stat function='add' value='200' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='6' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='8' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='0' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='5130' name="nos_sword">

        <stat function='add' value='5' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='5' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='12' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='-3' order='16' name='ACCURACY'/>
        <stat function='add' value='433' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='5131' name="parhit_staff">

        <stat function='add' value='5' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='5' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='12' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='-3' order='16' name='ACCURACY'/>
        <stat function='add' value='433' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='5132' name="giant_trident">

        <stat function='add' value='5' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='5' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='12' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='-3' order='16' name='ACCURACY'/>
        <stat function='add' value='433' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='5133' name="chrono_unitus">

        <stat function='add' value='1' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='1' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='4' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='4' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='5176' name="serpentine_spike">

        <stat function='add' value='17' order='16' name='PHYSIC_ATTACK'/>
        <stat function='add' value='21' order='16' name='MAGIC_ATTACK'/>
        <stat function='add' value='80' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='304' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
    <item id='5177' name="drake_horn">

        <stat function='add' value='19' order='16' name='PHYSIC_ATTACK'/>
        <stat function='add' value='24' order='16' name='MAGIC_ATTACK'/>
        <stat function='add' value='80' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='304' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
    <item id='5178' name="assult_alicorn">

        <stat function='add' value='21' order='16' name='PHYSIC_ATTACK'/>
        <stat function='add' value='27' order='16' name='MAGIC_ATTACK'/>
        <stat function='add' value='80' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='304' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
    <item id='5179' name="draconic_slicer">

        <stat function='add' value='23' order='16' name='PHYSIC_ATTACK'/>
        <stat function='add' value='30' order='16' name='MAGIC_ATTACK'/>
        <stat function='add' value='80' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='304' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
    <item id='5180' name="ohpdian_lance">

        <stat function='add' value='25' order='16' name='PHYSIC_ATTACK'/>
        <stat function='add' value='34' order='16' name='MAGIC_ATTACK'/>
        <stat function='add' value='80' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='304' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
    <item id='5181' name="diamond_drill">

        <stat function='add' value='27' order='16' name='PHYSIC_ATTACK'/>
        <stat function='add' value='37' order='16' name='MAGIC_ATTACK'/>
        <stat function='add' value='80' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='304' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
    <item id='5187' name="serpentine_grinder">

        <stat function='add' value='19' order='16' name='PHYSIC_ATTACK'/>
        <stat function='add' value='24' order='16' name='MAGIC_ATTACK'/>
        <stat function='add' value='80' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='304' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
    <item id='5188' name="fang_of_dahak">

        <stat function='add' value='21' order='16' name='PHYSIC_ATTACK'/>
        <stat function='add' value='27' order='16' name='MAGIC_ATTACK'/>
        <stat function='add' value='80' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='304' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
    <item id='5189' name="crimson_blood_fang">

        <stat function='add' value='23' order='16' name='PHYSIC_ATTACK'/>
        <stat function='add' value='30' order='16' name='MAGIC_ATTACK'/>
        <stat function='add' value='80' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='304' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
    <item id='5190' name="draconic_chopper">

        <stat function='add' value='25' order='16' name='PHYSIC_ATTACK'/>
        <stat function='add' value='34' order='16' name='MAGIC_ATTACK'/>
        <stat function='add' value='80' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='304' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
    <item id='5191' name="diabolic_grinder">

        <stat function='add' value='27' order='16' name='PHYSIC_ATTACK'/>
        <stat function='add' value='37' order='16' name='MAGIC_ATTACK'/>
        <stat function='add' value='80' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='304' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
</itemList>
