=== JoeAlisson/L2J/Datapack/data/stats/item.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://la2j.org"
           xmlns="http://la2j.org"
           elementFormDefault="qualified">

    <xs:include schemaLocation="stat.xsd"/>

    <xs:element name="itemList">
        <xs:complexType>
            <xs:choice>
                <xs:element name="item" type="xmlTypeItemStat" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
        </xs:complexType>

    </xs:element>

    <xs:complexType name="xmlTypeItemStat">
        <xs:sequence>
            <xs:element name="stat" type="xmlTypeStat" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:int" use="required"/>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

</xs:schema>

=== JoeAlisson/L2J/Datapack/data/stats/weapon/4200-4299.xml
<?xml version='1.0' encoding='utf-8'?>
<itemList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"           xmlns="http://la2j.org" xsi:schemaLocation="http://la2j.org ../item.xsd">
<item id='4202' name="chrono_cithara">

    <stat function='add' value='1' order='8' name='PHYSIC_ATTACK'/>
    <stat function='add' value='1' order='8' name='MAGIC_ATTACK'/>
    <stat function='add' value='8' order='8' name='CRITICAL_RATE'/>
    <stat function='add' value='0' order='16' name='ACCURACY'/>
    <stat function='add' value='379' order='8' name='PHYSIC_ATTACK_SPEED'/>
    <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
    <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

</item>
<item id='4219' name="dream_sword">

    <stat function='add' value='31' order='8' name='PHYSIC_ATTACK'/>
    <stat function='add' value='21' order='8' name='MAGIC_ATTACK'/>
    <stat function='add' value='8' order='8' name='CRITICAL_RATE'/>
    <stat function='add' value='0' order='16' name='ACCURACY'/>
    <stat function='add' value='379' order='8' name='PHYSIC_ATTACK_SPEED'/>
    <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
    <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

</item>
<item id='4220' name="dream_knife">

    <stat function='add' value='27' order='8' name='PHYSIC_ATTACK'/>
    <stat function='add' value='21' order='8' name='MAGIC_ATTACK'/>
    <stat function='add' value='12' order='8' name='CRITICAL_RATE'/>
    <stat function='add' value='-3' order='16' name='ACCURACY'/>
    <stat function='add' value='433' order='8' name='PHYSIC_ATTACK_SPEED'/>
    <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
    <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

</item>
<item id='4221' name="ubiquitous_axe">

    <stat function='add' value='31' order='8' name='PHYSIC_ATTACK'/>
    <stat function='add' value='21' order='8' name='MAGIC_ATTACK'/>
    <stat function='add' value='4' order='8' name='CRITICAL_RATE'/>
    <stat function='add' value='4' order='16' name='ACCURACY'/>
    <stat function='add' value='379' order='8' name='PHYSIC_ATTACK_SPEED'/>
    <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
    <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

</item>
<item id='4222' name="dream_shield">

    <stat function='sub' value='8' order='16' name='EVASION_RATE'/>
    <stat function='add' value='90' order='8' name='SHIELD_DEFENCE'/>
    <stat function='add' value='20' order='8' name='SHIELD_RATE'/>
    <stat function='enchant' value='0' order='12' name='PHYSIC_DEFENCE'/>

</item>
<item id='4223' name="ubiquitous_shield">

    <stat function='sub' value='8' order='16' name='EVASION_RATE'/>
    <stat function='add' value='90' order='8' name='SHIELD_DEFENCE'/>
    <stat function='add' value='20' order='8' name='SHIELD_RATE'/>
    <stat function='enchant' value='0' order='12' name='PHYSIC_DEFENCE'/>

</item>
<item id='4233' name="knuckle_duster">

    <stat function='add' value='148' order='8' name='PHYSIC_ATTACK'/>
    <stat function='add' value='68' order='8' name='MAGIC_ATTACK'/>
    <stat function='add' value='4' order='8' name='CRITICAL_RATE'/>
    <stat function='add' value='4' order='16' name='ACCURACY'/>
    <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>
    <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
    <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

</item>
<item id='4237' name="hatchlings_level_65_weapon">

    <stat function='add' value='24' order='16' name='PHYSIC_ATTACK'/>
    <stat function='add' value='32' order='16' name='MAGIC_ATTACK'/>
    <stat function='add' value='80' order='8' name='CRITICAL_RATE'/>
    <stat function='add' value='304' order='8' name='PHYSIC_ATTACK_SPEED'/>

</item>
<item id='4238' name="hatchlings_level_75_weapon">

    <stat function='add' value='31' order='16' name='PHYSIC_ATTACK'/>
    <stat function='add' value='43' order='16' name='MAGIC_ATTACK'/>
    <stat function='add' value='80' order='8' name='CRITICAL_RATE'/>
    <stat function='add' value='304' order='8' name='PHYSIC_ATTACK_SPEED'/>

</item>
</itemList>

=== JoeAlisson/L2J/Datapack/data/stats/armor/9200-9299.xml
<?xml version='1.0' encoding='utf-8'?>
<itemList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://la2j.org" xsi:schemaLocation="http://la2j.org ../item.xsd">
    <item id='9200' name="Jester Hat - Firework">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='9201' name="Wizard\'s Hat - Firework">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='9202' name="Dapper Hat - Firework">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='9203' name="Romantic Chapeau - Firework">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='9204' name="Iron Circlet - Firework">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='9208' name="Phantom Mask - For Events Only">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
</itemList>

=== JoeAlisson/L2J/Datapack/data/stats/armor/7600-7699.xml
<?xml version='1.0' encoding='utf-8'?>

<itemList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://la2j.org" xsi:schemaLocation="http://la2j.org ../item.xsd">
    <item id='7680' name="Raccoon Ear">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='7681' name="Outlaw's Eyepatch">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='7682' name="Maiden's Hairpin">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='7683' name="Rabbit Ear">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='7694' name="Noblesse Tiara">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='7695' name="Forget-me-not Hairpin">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='7696' name="Daisy Hairpin">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='7836' name="Santa's Hat">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='7837' name="Gold-line Mask">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
</itemList>

=== JoeAlisson/L2J/Datapack/data/stats/armor/5100-5199.xml
<?xml version='1.0' encoding='utf-8'?>

<itemList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://la2j.org" xsi:schemaLocation="http://la2j.org ../item.xsd">

    <item id='5170' name="Mithril Panzer Coat">

        <stat function='add' order='16' name='PHYSIC_DEFENCE' value='41'/>
        <stat function='add' order='16' name='MAGIC_DEFENCE' value='41'/>

    </item>
    <item id='5171' name="Brigadine Panzer Coat">

        <stat function='add' order='16' name='PHYSIC_DEFENCE' value='44'/>
        <stat function='add' order='16' name='MAGIC_DEFENCE' value='44'/>

    </item>
    <item id='5172' name="Draconic Panzer Coat">

        <stat function='add' order='16' name='PHYSIC_DEFENCE' value='46'/>
        <stat function='add' order='16' name='MAGIC_DEFENCE' value='46'/>

    </item>
    <item id='5173' name="Blood Panzer Coat">

        <stat function='add' order='16' name='PHYSIC_DEFENCE' value='49'/>
        <stat function='add' order='16' name='MAGIC_DEFENCE' value='49'/>

    </item>
    <item id='5174' name="Ophidian Panzer Coat">

        <stat function='add' order='16' name='PHYSIC_DEFENCE' value='52'/>
        <stat function='add' order='16' name='MAGIC_DEFENCE' value='52'/>

    </item>
    <item id='5175' name="Inferno Panzer Coat">

        <stat function='add' order='16' name='PHYSIC_DEFENCE' value='54'/>
        <stat function='add' order='16' name='MAGIC_DEFENCE' value='54'/>

    </item>
    <item id='5182' name="Hatchling's Gorgon Coat">

        <stat function='add' order='16' name='PHYSIC_DEFENCE' value='44'/>
        <stat function='add' order='16' name='MAGIC_DEFENCE' value='44'/>

    </item>
    <item id='5183' name="Hatchling's Ophidian Plate">

        <stat function='add' order='16' name='PHYSIC_DEFENCE' value='46'/>
        <stat function='add' order='16' name='MAGIC_DEFENCE' value='46'/>

    </item>
    <item id='5184' name="Hatchling's Crimson Plate">

        <stat function='add' order='16' name='PHYSIC_DEFENCE' value='49'/>
        <stat function='add' order='16' name='MAGIC_DEFENCE' value='49'/>

    </item>
    <item id='5185' name="Hatchling's Draconic Plate">

        <stat function='add' order='16' name='PHYSIC_DEFENCE' value='52'/>
        <stat function='add' order='16' name='MAGIC_DEFENCE' value='52'/>

    </item>
    <item id='5186' name="Hatchling's Inferno Plate">

        <stat function='add' order='16' name='PHYSIC_DEFENCE' value='54'/>
        <stat function='add' order='16' name='MAGIC_DEFENCE' value='54'/>

    </item>
</itemList>

=== JoeAlisson/L2J/Datapack/data/stats/armor/6600-6699.xml
<?xml version='1.0' encoding='utf-8'?>

<itemList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://la2j.org" xsi:schemaLocation="http://la2j.org ../item.xsd">

<item id='6656' name="Earring of Antharas">
  
    <stat function='add' value='71' order='16' name='MAGIC_DEFENCE'/>
    <stat function='add' value='31' order='64' name='MAX_MP'/>
    <stat function='enchant' value='0' order='12' name='MAGIC_DEFENCE'/>
   
</item>
<item id='6657' name="Necklace of Valakas">
  
    <stat function='add' value='95' order='16' name='MAGIC_DEFENCE'/>
    <stat function='add' value='42' order='64' name='MAX_MP'/>
    <stat function='enchant' value='0' order='12' name='MAGIC_DEFENCE'/>
  
</item>
<item id='6658' name="Ring of Baium">
  
    <stat function='add' value='48' order='16' name='MAGIC_DEFENCE'/>
    <stat function='add' value='21' order='64' name='MAX_MP'/>
    <stat function='enchant' value='0' order='12' name='MAGIC_DEFENCE'/>
  
</item>
<item id='6659' name="Zaken's Earring">
  
    <stat function='add' value='71' order='16' name='MAGIC_DEFENCE'/>
    <stat function='add' value='31' order='64' name='MAX_MP'/>
    <stat function='enchant' value='0' order='12' name='MAGIC_DEFENCE'/>
  
</item>
<item id='6660' name="Ring of Queen Ant">
  
    <stat function='add' value='48' order='16' name='MAGIC_DEFENCE'/>
    <stat function='add' value='21' order='64' name='MAX_MP'/>
    <stat function='enchant' value='0' order='12' name='MAGIC_DEFENCE'/>
  
</item>
<item id='6661' name="Earring of Orfen">
  
    <stat function='add' value='71' order='16' name='MAGIC_DEFENCE'/>
    <stat function='add' value='31' order='64' name='MAX_MP'/>
    <stat function='enchant' value='0' order='12' name='MAGIC_DEFENCE'/>
  
</item>
<item id='6662' name="Ring of Core">
  
    <stat function='add' value='48' order='16' name='MAGIC_DEFENCE'/>
    <stat function='add' value='21' order='64' name='MAX_MP'/>
    <stat function='enchant' value='0' order='12' name='MAGIC_DEFENCE'/>
  
</item>
<item id='6674' name="Sealed Imperial Crusader Breastplate">
  
    <stat function='add' value='193' order='16' name='PHYSIC_DEFENCE'/>
  
</item>
<item id='6675' name="Sealed Imperial Crusader Gaiters">
  
    <stat function='add' value='121' order='16' name='PHYSIC_DEFENCE'/>
  
</item>
<item id='6676' name="Sealed Imperial Crusader Gauntlet">
  
    <stat function='add' value='55' order='16' name='PHYSIC_DEFENCE'/>
  
</item>
<item id='6677' name="Sealed Imperial Crusader Boots">
  
    <stat function='add' value='55' order='16' name='PHYSIC_DEFENCE'/>
  
</item>
<item id='6679' name="Sealed Imperial Crusader Helmet">
  
    <stat function='add' value='83' order='16' name='PHYSIC_DEFENCE'/>
  
</item>
<item id='6680' name="Sealed Draconic Leather Armor">
  
    <stat function='add' value='236' order='16' name='PHYSIC_DEFENCE'/>
  
</item>
<item id='6681' name="Sealed Draconic Leather Glove">
  
    <stat function='add' value='55' order='16' name='PHYSIC_DEFENCE'/>
  
</item>
<item id='6682' name="Sealed Draconic Leather Boots">
  
    <stat function='add' value='55' order='16' name='PHYSIC_DEFENCE'/>
  
</item>
<item id='6683' name="Sealed Draconic Leather Helmet">
  
    <stat function='add' value='83' order='16' name='PHYSIC_DEFENCE'/>
  
</item>
<item id='6684' name="Sealed Major Arcana Robe">
  
    <stat function='add' value='157' order='16' name='PHYSIC_DEFENCE'/>
  
</item>
<item id='6685' name="Sealed Major Arcana Glove">
  
    <stat function='add' value='55' order='16' name='PHYSIC_DEFENCE'/>
  
</item>
<item id='6686' name="Sealed Major Arcana Boots">
  
    <stat function='add' value='55' order='16' name='PHYSIC_DEFENCE'/>
  
</item>
<item id='6687' name="Sealed Major Arcana Circlet">
  
    <stat function='add' value='83' order='16' name='PHYSIC_DEFENCE'/>
  
</item>
<item id='6724' name="Sealed Tateossian Earring">
  
    <stat function='add' value='68' order='16' name='MAGIC_DEFENCE'/>
    <stat function='enchant' value='0' order='12' name='MAGIC_DEFENCE'/>
  
</item>
<item id='6725' name="Sealed Tateossian Ring">
  
    <stat function='add' value='46' order='16' name='MAGIC_DEFENCE'/>
    <stat function='enchant' value='0' order='12' name='MAGIC_DEFENCE'/>
  
</item>
<item id='6726' name="Sealed Tateossian Necklace">
  
    <stat function='add' value='91' order='16' name='MAGIC_DEFENCE'/>
    <stat function='enchant' value='0' order='12' name='MAGIC_DEFENCE'/>
  
</item>
</itemList>

=== JoeAlisson/L2J/Datapack/data/stats/weapon/2300-2399.xml
<?xml version='1.0' encoding='utf-8'?>
<itemList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://la2j.org"
          xsi:schemaLocation="http://la2j.org ../item.xsd">
    <item id='2368' name="training_gloves">

        <stat function='add' value='7' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='5' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='4' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='4' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='2369' name="squires_sword">

        <stat function='add' value='6' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='5' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='8' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='0' order='16' name='ACCURACY'/>
        <stat function='add' value='379' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='2370' name="guild_members_club">

        <stat function='add' value='6' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='5' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='4' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='4' order='16' name='ACCURACY'/>
        <stat function='add' value='379' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='2371' name="fist_of_butcher">

        <stat function='add' value='16' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='10' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='4' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='4' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='2372' name="dagger_of_adept">

        <stat function='add' value='11' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='10' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='12' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='-3' order='16' name='ACCURACY'/>
        <stat function='add' value='433' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='2373' name="eldritch_staff">

        <stat function='add' value='13' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='13' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='4' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='4' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='2374' name="red_sunset_dagger">

        <stat function='add' value='11' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='10' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='12' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='-3' order='16' name='ACCURACY'/>
        <stat function='add' value='433' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
</itemList>

=== JoeAlisson/L2J/Datapack/data/stats/weapon/3000-3099.xml
<?xml version='1.0' encoding='utf-8'?>
<itemList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://la2j.org"
          xsi:schemaLocation="http://la2j.org ../item.xsd">
    <item id='3026' name="talins_spear">

        <stat function='add' value='24' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='17' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='8' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='66' order='8' name='PHYSIC_ATTACK_RANGE'/>
        <stat function='add' value='-3' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='3027' name="old_knights_sword">

        <stat function='add' value='29' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='17' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='8' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='0' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='3028' name="crescent_moon_bow">

        <stat function='add' value='34' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='12' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='12' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='-3' order='16' name='ACCURACY'/>
        <stat function='add' value='293' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='3029' name="sword_of_binding">

        <stat function='add' value='17' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='12' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='8' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='0' order='16' name='ACCURACY'/>
        <stat function='add' value='379' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
</itemList>

=== JoeAlisson/L2J/Datapack/data/stats/armor/0000-0099.xml
<?xml version='1.0' encoding='utf-8'?>

<itemList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://la2j.org" xsi:schemaLocation="http://la2j.org ../item.xsd">

    <item id="21" name="Shirt">
        <stat function="add" order="10" val="36">PHYSIC_DEFENCE</stat>
    </item>

    <item id='21' name="Shirt">
        <stat function="add" val='36' order='10'>PHYSIC_DEFENCE</stat>
    </item>

    <item id='22' name="Leather Shirt">
        <stat function="add" val='43' order='10'>PHYSIC_DEFENCE</stat>
    </item>

    <item id='23' name="Wooden Breastplate">
        <stat function="add" order='10' val='47'>PHYSIC_DEFENCE</stat>
    </item>

    <item id='24' name="Bone Breastplate">
        <stat function="add" val='50' order='10'>PHYSIC_DEFENCE</stat>
    </item>

    <item id='25' name="Piece Bone Breastplate">
        <stat function="add" val='62' order='10' >PHYSIC_DEFENCE</stat>
    </item>

    <item id='26' name="Bronze Breastplate">
        <stat function="add" val='68' order='10' >PHYSIC_DEFENCE</stat>
    </item>

    <item id='27' name="Hard Leather Shirt">
        <stat function="add" val='53' order='10' >PHYSIC_DEFENCE</stat>
    </item>

    <item id='28' name="Pants">
        <stat function="add" val='22' order='10' >PHYSIC_DEFENCE</stat>
    </item>

    <item id='29' name="Leather Pants">
        <stat function="add" val='27' order='10' >PHYSIC_DEFENCE</stat>
    </item>

    <item id='30' name="Hard Leather Pants">
        <stat function="add" val='29' order='10' >PHYSIC_DEFENCE</stat>
    </item>

    <item id='31' name="Bone Gaiters">
        <stat function="add" val='32' order='10' >PHYSIC_DEFENCE</stat>
    </item>

    <item id='32' name="Piece Bone Gaiters">
        <stat function="add" val='39' order='10' >PHYSIC_DEFENCE</stat>
    </item>

    <item id='33' name="Hard Leather Gaiters">
        <stat function="add" val='33' order='10' >PHYSIC_DEFENCE</stat>
    </item>

    <item id='34' name="Bronze Gaiters">
        <stat function="add" val='43' order='10' >PHYSIC_DEFENCE</stat>
    </item>

    <item id='35' name="Cloth Shoes">
        <stat function="add" val='9' order='10' >PHYSIC_DEFENCE</stat>
    </item>

    <item id='36' name="Leather Sandals">
        <stat function="add" val='9' order='10' >PHYSIC_DEFENCE</stat>
    </item>

    <item id='37' name="Leather Shoes">
        <stat function="add" val='13' order='10' >PHYSIC_DEFENCE</stat>
    </item>

    <item id='38' name="Low Boots">
        <stat function="add" val='15' order='10' >PHYSIC_DEFENCE</stat>
    </item>

    <item id='39' name="Boots">
        <stat function="add" val='17' order='10' >PHYSIC_DEFENCE</stat>
    </item>

    <item id='40' name="Leather Boots">
        <stat function="add" val='19' order='10' >PHYSIC_DEFENCE</stat>
        <stat function="enchant" val='0' order='12'>PHYSIC_DEFENCE</stat>
    </item>

    <item id='41' name="Cloth Cap">
        <stat function="add" val='13' order='10' >PHYSIC_DEFENCE</stat>
    </item>

    <item id='42' name="Leather Cap">
        <stat function="add" val='16' order='10' >PHYSIC_DEFENCE</stat>
    </item>

    <item id='43' name="Wooden Helmet">
        <stat function="add" val='19' order='10' >PHYSIC_DEFENCE</stat>
    </item>

    <item id='44' name="Leather Helmet">
        <stat function="add" val='23' order='10' >PHYSIC_DEFENCE</stat>
    </item>

    <item id='45' name="Bone Helmet">
        <stat function="add" val='29' order='10' >PHYSIC_DEFENCE</stat>
        <stat function="enchant" val='0' order='12' >PHYSIC_DEFENCE</stat>
    </item>

    <item id='46' name="Bronze Helmet">
        <stat function="add" val='33' order='10' >PHYSIC_DEFENCE</stat>
        <stat function="" val='0' order='12' >PHYSIC_DEFENCE</stat>
    </item>

    <item id='47' name="Helmet">
        <stat function="add" val='37' order='10' >PHYSIC_DEFENCE</stat>
        <stat function="enchant" val='0' order='12' >PHYSIC_DEFENCE</stat>
    </item>

    <item id='48' name="Short Gloves">
        <stat function="add" val='9' order='10' >PHYSIC_DEFENCE</stat>
    </item>

    <item id='49' name="Gloves">
        <stat function="add" val='13' order='10' >PHYSIC_DEFENCE</stat>
    </item>

    <item id='50' name="Leather Gloves">
        <stat function="add" val='15' order='10' >PHYSIC_DEFENCE</stat>
    </item>

    <item id='51' name="Bracer">
        <stat function="add" val='17' order='10' >PHYSIC_DEFENCE</stat>
    </item>

    <item id='52' name="Hemp Cloak">
        <stat function="add" val='2' order='10' >PHYSIC_DEFENCE</stat>
    </item>

    <item id='53' name="Cotton Cloak">
        <stat function="add" val='3' order='10' >PHYSIC_DEFENCE</stat>
    </item>

    <item id='54' name="Silk Cloak">
        <stat function="add" val='4' order='10' >PHYSIC_DEFENCE</stat>
    </item>

    <item id='55' name="Cotton Undergarment">
        <stat function="add" val='4' order='10' >PHYSIC_DEFENCE</stat>
    </item>

    <item id='56' name="Wool Undergarment">
        <stat function="add" val='5' order='10' >PHYSIC_DEFENCE</stat>
    </item>

    <item id='58' name="Mithril Breastplate">
        <stat function="add" val='95' order='10' >PHYSIC_DEFENCE</stat>
        <stat function="enchant" val='0' order='12' >PHYSIC_DEFENCE</stat>
    </item>

    <item id='59' name="Mithril Gaiters">
        <stat function="add" val='61' order='10' >PHYSIC_DEFENCE</stat>
        <stat function="enchant" val='0' order='12' >PHYSIC_DEFENCE</stat>
    </item>

    <item id='60' name="Composite Armor">
        <stat function="add" val='224' order='10' >PHYSIC_DEFENCE</stat>
        <stat function="enchant" val='0' order='12' >PHYSIC_DEFENCE</stat>
    </item>

    <item id='61' name="Mithril Gloves">
        <stat function="add" val='29' order='10' >PHYSIC_DEFENCE</stat>
        <stat function="enchant" val='0' order='12' >PHYSIC_DEFENCE</stat>
    </item>

    <item id='62' name="Mithril Boots">
        <stat function="add" val='32' order='10' >PHYSIC_DEFENCE</stat>
        <stat function="enchant" val='0' order='12' >PHYSIC_DEFENCE</stat>
    </item>

    <item id='63' name="Gauntlets">
        <stat function="add" val='24' order='10' >PHYSIC_DEFENCE</stat>
        <stat function="enchant" val='0' order='12' >PHYSIC_DEFENCE</stat>
    </item>

    <item id='64' name="Composite Boots">
        <stat function="add" val='36' order='10' >PHYSIC_DEFENCE</stat>
        <stat function="enchant" val='0' order='12' >PHYSIC_DEFENCE</stat>
    </item>

</itemList>
